### PR TITLE
Updated to Fastify v5

### PR DESCRIPTION
**Pull request by EmmanuelBeziat**
Found no breaking changes in code so far. Tested with my 2 apps, worked smoothly.

Not sure why the diff shows so much differences in files tho, I only changed versions lines.

### CODE REVIEW

**Comment by smartiniOnGitHub** [comment]
Hi, thanks for changes, I'll do some checks and publish a new version in a few days.

**Comment by smartiniOnGitHub** [comment]
Hi, as usual I just completed to update all dependencies to latest (latest TAP gave me some trouble to fix/simplify commands and config for tests), require Node.js 20 LTS as minimum version (as per best practices), update year in sources, documentation, etc so all should be fine.
Last I only need to update release date in changelog file, but now is late; soon I should be able to publish this new major version of the plugin.
Thanks for the help on it. Bye

**Comment by EmmanuelBeziat** [comment]
Thank you! :) Yeah I didn't touch the changelog for I suspected that you would have to make a few minor adjustments.

**Comment by smartiniOnGitHub** [comment]
Hi, plugin version 5.0.0 just published. Bye

**Comment by EmmanuelBeziat** [comment]
Thanks!

**Pull request merged**
